### PR TITLE
Update contact manager for Gazebo 2.0

### LINKED ISSUE #7: Fix ABI/API breakages coming with Gazebo 2.0
Gazebo 2.0 breaks API and ABI compatibility at various points. So far I spotted the following:
- [x] new paths for gazebo header includes, e.g. `common/common.hh` -> `gazebo/common/common.hh`
- [ ] collision/contact detection is done differently

### PR DESCRIPTION
**Pull request by trainman419**
I've updated the gazebo create plugin for Gazebo2. It's late and I don't have time to test it, but it at least seems sound and it compiles.

This should resolve #7 

It may also be worth consolidating the hydro, hydro-devel and indigo branches; it looks like they've diverged, and there are changes in the hydro branch that haven't made it to the indigo branch yet...

### CODE REVIEW

**Comment by trainman419** [comment]
It looks like the contact manager is being used to simulate drop sensors. Testing that those work properly in simulation may be tricky.

**Comment by bit-pirate** [comment]
Have you checked the kobuki plugin? We probably had to jump through the
same hoops.

On 19 November 2014 18:47, Austin notifications@github.com wrote:

> It looks like the contact manager is being used to simulate drop sensors.
> Testing that those work properly in simulation may be tricky.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/turtlebot/turtlebot_create_desktop/pull/16#issuecomment-63614760
> .

## 

Innovation Team Leader
Yujin Robot
Seoul, Republic of Korea
Twitter: @yujinrobotinno
Website: http://inno.yujinrobot.com
Email: marcus.liebhardt@yujinrobot.com
Phone: +82-70-46577073

**Comment by trainman419** [comment]
There's an [open issue](https://github.com/yujinrobot/kobuki_desktop/issues/22), but no resolution, and I haven't been able to find a commit in the kobuki_desktop repository that makes similar changes.

I suspect the kobuki simulator is simulating the drop sensors differently.

**Comment by trainman419** [comment]
Scratch that; the contact detection is actually simulating the bump sensors. The kobuki node does this differently, by polling the bumper for contacts instead of subscribing to the contacts from the simulator, and this is why this issue isn't present in the kobuki gazebo plugin.

I ran it through gazebo a bit, and it runs, but it doesn't appear to detect bumps properly. Otherwise, it seems to work ok.

**Comment by trainman419** [comment]
At least part of the problem with the bump detection is that there are no contacts between the base and the world, because the collision geometry is too small. See: https://github.com/trainman419/turtlebot_create/commit/21ccdc4427399e99845728cbd8259b9260aa412b

With that fixed, and contacts properly generated, it still looks like contacts aren't properly filtered or subscribed to. At this point it probably needs someone who knows gazebo better than I do.

I'm starting to wonder if this ever worked, and if we should just release it with my partial fix, and fix the remaining issues later.

**Comment by jihoonl** [comment]
Yeah agree

**Comment by jihoonl** [comment]
thanks for the fix.

**Pull request merged**
